import test from 'node:test';
import assert from 'node:assert/strict';
import {sendSubmission} from '../dist/data.js';
import {questions} from '../dist/questions.js';
const settings={supabaseUrl:'https://example.supabase.co',supabasePublishableKey:'sb_publishable_test'};
const payload=()=>({id:'9e486f9c-c79e-4a53-a9ca-af2175d158c2',name:'Test',consent:true,version:'1',answers:questions.map(q=>({id:q.id,value:null}))});
test('Le mode aperçu ne fait aucun appel réseau',async()=>{let calls=0;await assert.rejects(()=>sendSubmission(payload(),{settings:{supabaseUrl:'',supabasePublishableKey:''},fetcher:()=>calls++}),/aperçu/);assert.equal(calls,0);});
test('Aucun envoi sans accord explicite',async()=>{let calls=0;await assert.rejects(()=>sendSubmission({...payload(),consent:false},{settings,fetcher:()=>calls++}),/accord/);assert.equal(calls,0);});
test('Un échec réseau ne produit pas une confirmation de sauvegarde',async()=>{await assert.rejects(()=>sendSubmission(payload(),{settings,fetcher:async()=>{throw new TypeError('network');}}),/connexion/);});
test('Un refus serveur reste un échec',async()=>{await assert.rejects(()=>sendSubmission(payload(),{settings,fetcher:async()=>new Response('',{status:403})}),/pas été confirmé/);});
test('Une réponse inattendue ne produit pas une confirmation de sauvegarde',async()=>{await assert.rejects(()=>sendSubmission(payload(),{settings,fetcher:async()=>Response.json('un-autre-identifiant')}),/pas été confirmé/);});
test('Un nouvel essai garde le même identifiant pour éviter les doublons',async()=>{const requests=[];const data=payload();const fetcher=async(url,options)=>{requests.push(JSON.parse(options.body));assert.equal(options.headers.apikey,settings.supabasePublishableKey);assert.match(url,/rpc\/submit_answers$/);return Response.json(data.id);};assert.equal(await sendSubmission(data,{settings,fetcher}),data.id);await sendSubmission(data,{settings,fetcher});assert.deepEqual(requests[0],requests[1]);});
